name: Code workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-validation:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Render Deployment
      uses: sws2apps/render-deployment@v1.6.0
      with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
    